using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.SceneManagement;
using UnityEngine.UIElements;

namespace Depths.Unity
{
    /// <summary>
    /// Placeholder for the game scene until tickBodies and tickProjectiles are ported. It draws floor
    /// 1 of a seed as generated by Depths.Core - the same rooms the JavaScript builds for that seed -
    /// which proves the simulation runs inside Unity. Esc: menu. R: another seed.
    /// </summary>
    [RequireComponent(typeof(UIDocument))]
    public sealed class GameView : MonoBehaviour
    {
        const float Cell = 64f, Pad = 12f;
        uint _seed;

        bool _dirty = true;

        // Drawn from Update once the document root is live in a panel. Drawing in OnEnable or Start put
        // the rooms into a tree UIDocument then replaced (measured: panel null, layout NaN), so the scene was blank.
        void Start() { _seed = NewSeed(); }

        static uint NewSeed() => (uint)Random.Range(int.MinValue, int.MaxValue);

        void Update()
        {
            if (_dirty)
            {
                var r = GetComponent<UIDocument>().rootVisualElement?.Q("gameRoot");
                if (r != null && r.panel != null) { Draw(r); _dirty = false; }
            }
            var k = Keyboard.current;
            if (k == null) return;
            if (k.escapeKey.wasPressedThisFrame) SceneManager.LoadScene("MainMenu");
            if (k.rKey.wasPressedThisFrame) { _seed = NewSeed(); _dirty = true; }
        }

        void Draw(VisualElement root)
        {
            root.Clear();
            root.style.backgroundColor = new Color(11 / 255f, 13 / 255f, 18 / 255f);
            var dungeon = Dungeon.FromSeed(new Rng(_seed));
            var map = new VisualElement();
            map.style.position = Position.Absolute;
            map.style.left = 700;
            map.style.top = 150;
            foreach (var r in dungeon.AllRooms)
            {
                var box = new VisualElement();
                box.AddToClassList("game-room");
                box.AddToClassList(r.Type.ToString().ToLowerInvariant());
                box.style.left = r.X * Cell + Pad / 2;
                box.style.top = r.Y * Cell + Pad / 2;
                box.style.width = Cell - Pad;
                box.style.height = Cell - Pad;
                map.Add(box);
                foreach (var d in r.Doors)
                {
                    var door = new VisualElement();
                    door.AddToClassList("game-door");
                    float cx = r.X * Cell + Cell / 2, cy = r.Y * Cell + Cell / 2;
                    bool horiz = d == Dir.E || d == Dir.W;
                    door.style.width = horiz ? Pad : 8;
                    door.style.height = horiz ? 8 : Pad;
                    door.style.left = cx + (d == Dir.E ? Cell / 2 - Pad / 2 : d == Dir.W ? -Cell / 2 - Pad / 2 : -4);
                    door.style.top = cy + (d == Dir.S ? Cell / 2 - Pad / 2 : d == Dir.N ? -Cell / 2 - Pad / 2 : -4);
                    map.Add(door);
                }
            }
            root.Add(map);
            var text = new Label("SEED " + Rng.Encode(_seed) + "   floor 1, " + dungeon.AllRooms.Count + " rooms\n\n" +
                "Generated by Depths.Core: the same floor the JavaScript game builds for this seed.\n" +
                "The playable port lands with tickBodies and tickProjectiles.\n\nR  another seed      Esc  menu");
            text.AddToClassList("game-text");
            root.Add(text);
        }
    }
}
