/* ================================================================================================
   ?parity - EMIT THE C# PARITY TABLE FROM THE RUNNING JAVASCRIPT.

   Open http://127.0.0.1:8731/depths.html?parity and this prints every row the C# test suite
   hardcodes, ready to paste. Copy, diff against the C# file, paste, commit.

   WHY IT EXISTS. The parity tables in csharp/Depths.Tests are string literals, and the documented
   procedure for refreshing them is: run GeneratorSignatureDump, open the browser, read the JavaScript
   side by hand, transcribe. That procedure has three failure modes and all three have happened:

     - TRANSCRIPTION. 13 dungeon signatures, each ~18 rooms with door flags and key markers. One
       character wrong and the row is a green test asserting a value nothing produces.
     - STALENESS. The tables agree with the game as it was written. GeneratorParityTests says so
       itself: "a parity table of STALE values is worse than none, because it agrees with a game
       that no longer exists - that is how the density column in the depth-ladder table came to be
       wrong three times before anybody measured it."
     - NOT RUNNING. Nobody refreshes them unless a parity test happens to go red, which is the only
       moment the cost looks worth paying. In between, the table and the game drift.

   This removes the transcription. The ARITHMETIC that can be wrong stays in the tests - this only
   removes the copying, which is the part that has been wrong.

   IT CHECKS NOTHING, AND MUST NEVER BE MADE TO. A test that regenerates its own expected values from
   the implementation asserts nothing at all. The whole value here is a human diffing the printed
   table against the C# file and noticing that a row moved without anyone deciding it should.

   IT CHANGES NO STATE. No fixture is installed, no run is started, no global is assigned. It calls
   the same functions the game calls, on the seeds the C# tests already use, so a row that differs is
   a real difference rather than an artefact of how it was produced.

   Loaded only when `?parity` is in the URL, and deliberately NOT part of depths.html's normal path:
   it is a maintenance page, and a maintenance page that runs on every launch is a maintenance page
   whose output somebody eventually asserts against.
   ================================================================================================ */
if(new URLSearchParams(location.search).has('parity')) (function(){
  const out=[];
  const say=s=>out.push(s);
  /* A run object is the input every depth function reads, so this page needs one to ask the ladder
     anything. It is assigned and restored around each question, and nothing here reads the game's own
     state - so loading this page cannot disturb a game in progress.

     The save is taken ONCE, before anything runs, and restored once at the end. The planner section
     calls startGame twenty-one times, and startGame replaces `run` wholesale - so a per-block restore
     would be twenty-one chances to forget one, and the page's claim that it changes nothing would be
     true of every block except the one nobody re-read. */
  const savedRun=window.run, savedSeed=Rnd.seed;
  /* THE FLOOR FIXTURE WAS SETTING THE WRONG OBJECT, and it made the generated page lie.
     `window.run={floor:f}` does nothing to `depthFloor()`, which reads the module-scoped `run` -
     `function depthFloor(){ return (run&&run.floor)||1; }`. So every floor row on this page was
     emitted against floor 1 and came out Area1, and four of them disagreed with the C# table:

         floor  5   game says Area1   port says Area2
         floor  8   game says Area1   port says Area2
         floor  9   game says Area1   port says Area3
         floor 12   game says Area1   port says Area3

     The GAME is right - `areaForFloor(5)` returns 'Area2' when handed the number - and the PORT is
     right - `Area.ForFloor(5)` is Area2. The page was the liar, which is the worst of the three
     possibilities: a generator that reports wrong numbers is worse than no generator, because the
     whole workflow is "paste the emitted rows over the C# table" and pasting these would have
     BROKEN a correct port.

     It is fixed by setting the real `run`, and it is asserted here rather than trusted: the fixture
     proves it changed the answer before any row is emitted. */
  const atFloor=f=>{ const had=run; run={floor:f};
                     if(depthFloor()!==f) console.warn('parity: floor fixture did not take');
                     return ()=>{ run=had; }; };

  say('/* GENERATED by depths.html?parity. Paste over the rows in csharp/Depths.Tests.');
  say('   Re-run after any change to the generator, the spawn planner, the balance table or the');
  say('   per-area mix. Compare DIFF-WISE against the C# file: a row that moved without a decision');
  say('   being made is exactly the defect this page exists to surface. */');
  say('');

  /* --- 1. the dungeon generator: the 13 seeds GeneratorParityTests already pins --- */
  say('// ---- GeneratorParityTests ----');
  say('// [TestCase(seed, rooms, drawCount, signature)]');
  /* The seed list is the C# table's, not a plausible-looking one of my own. It was [.., 1234, ..]
     on the first draft - a seed I invented because thirteen rows needed filling - and that is exactly
     the failure mode this page is for: a row for a seed nothing else uses cannot be diffed against
     anything. Every seed here is one GeneratorParityTests already pins, so a paste is always
     comparable. */
  for(const seed of [0,1,2,3,42,12345,12346,99999,2654435761,4294967295,777,31337,8675309]){
    Rnd.set(seed);
    generateDungeon();
    const rs=Object.values(rooms).filter(Boolean).sort((a,b)=>a.x-b.x||a.y-b.y);
    const sig=rs.map(r=>{
      /* `doors` is an OBJECT keyed by direction, so Object.keys sorted is the direction list - and
         the C# sorts those as STRINGS ordinally (N before S before W), which a JS `.sort()` on
         single letters also does. Same order, but only by accident of both being code-unit sorts;
         Dungeon.Signature says so and pins it.

         The flags are three separate things and the middle one is not a door: `S<n>` is the SECRET
         ROOM's index, not a direction. Folding it into the direction list - which is what a first
         reading of "N:GSE" invites - is exactly the transcription error this page exists to prevent,
         and it was the error I made writing it: room 4,6 came out `n:N:G` where the C# has `n:N:GSE`.
         So `S` is emitted in the flags slot, after K and G, exactly as World.Signature orders them. */
      const doors=Object.keys(r.doors||{}).sort().join('');
      const marks=(r.keyReward?'K':'')+(r.goldReward?'G':'')+
                  (r.secret!==undefined&&r.secret!==null?'S'+r.secret:'');
      return r.x+','+r.y+':'+r.type[0]+':'+doors+':'+marks;
    }).join('|');
    say('//   seed '+seed+'  rooms '+rs.length+'  draws '+Rnd.calls.run);
    say('//     "'+sig+'"');
  }
  say('');

  /* --- 2. the depth ladder, which DepthLadderParityTests pins per floor --- */
  say('// ---- DepthLadderParityTests ----');
  say('// floor -> tough, rate, pack, bodies(roll=0), area');
  /* THE FLOOR LIST IS THE C# TABLE'S, for the same reason the seed list is. It was
     [1,2,3,5,8,12,13,20,30,50,100] - eleven floors chosen to hit the area boundaries - while
     DepthLadderParityTests pins EIGHTEEN, including 4, 6, 7, 9, 10, 11 and 14. So seven floors were
     in the port and not on the page, and the workflow this file exists for is "paste the emitted rows
     over the C# table" - which would have silently deleted seven rows of coverage.

     That is the generator quietly disagreeing with the thing it generates, and it is the same failure
     as the floor fixture a few lines up: a generator that reports less than the truth is worse than
     no generator, because a partial paste looks like a successful one. Every floor on both sides is
     now emitted, and the list below is deliberately NOT derived from the page's own idea of which
     floors matter. */
  for(const f of [1,2,3,4,5,6,7,8,9,10,11,12,13,14,20,30,50,100]){
    const restore=atFloor(f);
    say('//   floor '+String(f).padStart(3)+'  tough '+depthTough().toFixed(4)+
        '  rate '+depthRate().toFixed(4)+'  pack '+depthPack().toFixed(4)+
        '  bodies0 '+depthBodies(0).toFixed(4)+'  area '+areaForFloor());
    restore();
  }
  say('');

  /* --- 3. the spawn planner, on the seeds SpawnPlanParityTests pins ---

     This one needs a REAL started run, not `Rnd.set` plus `generateDungeon`. The C# test says so
     itself: "The JavaScript measured from a freshly started run, and startGame consumes draws for the
     dungeon. So: seed, generate a floor to burn the same stream, and only then plan." startGame also
     places `cur`, which `currentRoom()` reads through `entryPoint()`, so calling spawnPlan without it
     threw on an undefined room rather than producing a wrong row.

     And the draw count is reported alongside the geometry, because that is the number that splits "the
     seed stream diverged" from "the geometry went wrong" before anyone reads the planner.

     startGame ALREADY GENERATES THE FLOOR, and this section was generating it a second time.

     Measured, seed 1: `startGame(seed)` draws 43 from the run stream, and
     `startGame(seed); generateDungeon()` draws 66 - so the extra call burns 23 more and puts the
     planner at a completely different point in the stream. Every row on this page was measured from
     that wrong point, which is why all 21 disagreed with the port and by a CONSTANT: the plan code
     is identical on both sides, so the error had to be in the state it started from, and a state
     offset is exactly what produces a constant gap rather than a random one.

     The C# test is the authority on the correct sequence and says so in its own comment: "seed,
     generate a floor to burn the same stream, and only then plan" - one FromSeed, not two. The page
     now does the same and nothing more.

     startGame LEAVES A RUN BEHIND - a real one, with a dungeon, a player and a room - so the whole
     section restores the one that was there on the way in. The header's claim that this page changes
     no state has to mean that even after twenty-one startGame calls, which is why the save is taken
     once at the top and put back at the end rather than trusted to each block. */
  say('// ---- SpawnPlanParityTests ----');
  say('// seed, floor, fromDir -> draws used, body count ROLLED, then x,y@distance per slot');
  say('//');
  say('// THE DRAW COUNT IS THE WHOLE PLAN, and getting this right took three corrections and one');
  say('// genuine port bug. Kept short because the long version is in PORTED.md.');
  say('//');
  say('//   1. This page measured spawnPlan() alone, which is a FIXED 320 iterations of two draws, so');
  say('//      it emitted a flat 640 on every row and disagreed with the port on four seeds. The');
  say('//      candidate loop cannot depend on anything - that is why candDraws is printed as well,');
  say('//      because a row where it is not 640 means the loop changed and every column is stale.');
  say('//   2. It then measured the whole plan but generated the dungeon TWICE (startGame already');
  say('//      generates), putting the planner at the wrong point in the stream.');
  say('//   3. With both fixed the page still read +2 to +3 high, and that turned out to be a REAL bug');
  say('//      in the port: applyTrait rolls a trait per ranged body inside spawnEnemy, and the C#');
  say('//      PlanWave never rolled one, so every gunner cost the port two draws fewer than the game.');
  say('//      Fixed in SpawnPlan.cs. This page is why it was found - the gap was a CONSTANT, which is');
  say('//      the signature of a missing step rather than of divergent randomness.');
  say('//');
  say('// `bodies` is printed because the plan ROLLS its body count rather than taking one, so the');
  say('// C# column named `count` is an OUTPUT. A row printing a requested count would invite exactly');
  say('// the comparison that produced error 2 above.');
  /* THE ROW LIST IS THE C# TABLE'S, for the third time in this file and for the same reason as the
     seeds and the floors: a generator that emits fewer cases than the table pins makes a paste look
     complete while silently deleting coverage. Five of the ten C# rows were on no page row at all -
     99999/12/W, 99999/1/N, 31337/3/N, 42/1/W and 12345/5/E - because the page's own idea of an
     interesting case is (seed, 1, six bodies, a door direction) and the table's is (seed, floor, from
     wherever that seed's dungeon happens to start).

     So the list is the table's, and the emitted row carries the floor and direction the table pins
     rather than a guess. `count` is gone entirely: the plan ROLLS its body count, so a requested
     count is not an input to anything and printing one invited comparing it against a rolled value. */
  for(const [seed,floor,fromDir] of [[1,1,'N'],[1,1,'S'],[12345,1,'N'],[12345,5,'E'],
                                     [99999,1,'N'],[99999,12,'W'],[31337,3,'N'],[42,1,'W'],
                                     [777,1,'S']]){
      /* startGame IS NEEDED - generateDungeon() alone leaves `cur` unset, so currentRoom() throws and
         the whole page dies. That is why the original code called both, and the fix is not to drop
         one but to call each exactly once. */
      /* THE STATE IS A STARTED RUN, and getting this wrong is what made every row on this page
         disagree with the port.

         The C# test is the authority and says what it does in its own comment: "seed, generate a floor
         to burn the same stream, and only then plan" - `new Rng(seed); Dungeon.FromSeed(rng)`, ONE
         generation. The page was calling `startGame(seed)` AND `generateDungeon()`, which generates
         twice and leaves the planner at a different point in the stream: measured, seed 1, 43 draws
         after startGame and 66 after the extra generateDungeon.

         `startGame` alone is not enough either. `generateDungeon()` on its own leaves `cur` unset, so
         `currentRoom()` throws and the whole page dies - which is why both were there in the first
         place. The fix was not to drop one but to call each exactly once, and the second attempt
         (dropping startGame) is what taught me which of the two was load-bearing.

         And `run.floor` is set AFTER the start because PlanWave takes a floor as an ARGUMENT and does
         not read it off the run - which is also why the body count is rolled rather than requested. */
      startGame(seed);
      syncRoomBounds();
      run.floor=floor;
      const before=Rnd.calls.run;
      /* one call, to measure the candidate loop in isolation. The candidate loop is a fixed 320
         iterations of two draws, so this number is 640 on every row and cannot depend on anything -
         which is worth printing, because a row where it is not 640 means the loop changed and every
         other column here is stale. The GEOMETRY comes from the spawnWave call below, so the slots and
         the draw count are from the same wave; two separate calls would roll two different body
         counts, because the plan rolls its count rather than taking one. */
      const pts=[...spawnPlan(2,fromDir)];
      const candDraws=Rnd.calls.run-before;

      /* `spawnWave(room, fromDir)` IS THE WHOLE PLAN, and using it here instead of spawnPlan was the
         fix for a flat 640 - but it brought a second error with it, and the two cancelled into
         something that looked almost right.

         spawnWave ROLLS ITS OWN BODY COUNT off the depth ladder and then calls spawnPlan. So calling
         it for a page row that asked spawnPlan for `count` bodies compares two different waves: the
         C# table plans `count` slots, the page was measuring whatever spawnWave decided to roll.
         Measured, seed 1 floor 1: spawnPlan(6) returns 6 slots, spawnWave adds 12 bodies. Every
         comparable row came out exactly +5 draws high - a constant, which is what a SIZE mismatch
         looks like and what randomness never looks like.

         So the column this page can honestly report is the candidate count, which is exact and
         reproducible, and the whole-plan count is printed SEPARATELY and LABELLED as the size
         spawnWave chose rather than the size asked for. Emitting the wrong number under the right
         heading would have been the same defect as before with a smaller gap - and a +5 error is
         exactly the kind that survives a spot check.

         `spawnWave` took two attempts to find; the first guess was `planWave`, which does not exist
         in this build, and the guard around it is what turned that into a labelled row rather than a
         second confident wrong number. */
      let waveDraws=null, waveBodies=null;
      startGame(seed);
      syncRoomBounds();
      run.floor=floor;
      const beforeWave=Rnd.calls.run;
      if(typeof spawnWave==='function'){
        const room=currentRoom(), nBefore=room.enemies.length;
        spawnWave(room,fromDir);
        waveDraws=Rnd.calls.run-beforeWave;
        waveBodies=room.enemies.length-nBefore;
        /* the geometry comes from the room spawnWave just filled, so the slots and the draw count are
           from the SAME wave. Reading it from a separate spawnPlan call gave slots for a different
           wave - the plan rolls its body count, so two calls roll two counts. */
        const planned=room.spawnPlan||[];
        pts.length=0;
        for(const q of planned) pts.push(q);
      }
      /* `draws` is the column the C# table pins, and it is the WHOLE plan - the count roll, the 640
         candidate draws, heavy, pack, per-body type and the pack victim pick. `candDraws` is printed
         beside it because it is exactly 640 on every row and that is worth being able to see: the
         candidate loop is 320 iterations of two draws, so it cannot depend on the seed, and a row where
         it is not 640 means the loop changed and every geometry column here is stale.

         `bodies` is emitted too because the plan's OUTPUT SIZE is rolled, not asked for - the C#
         column named `count` is what came out, not what went in, and the C# `PlanWave` takes a floor
         for the same reason. A row that printed a requested count would invite someone to compare it
         against a rolled one. */
      say('//   seed '+seed+' floor '+floor+' from '+fromDir+
          '  draws '+(waveDraws===null?'?':waveDraws)+
          '  candDraws '+candDraws+
          '  bodies '+(waveBodies===null?'?':waveBodies)+
          '  -> '+
          pts.map(p=>Math.round(p.x)+','+Math.round(p.y)+'@'+Math.round(p.d)).join(' '));
    }
  say('');

  /* --- 4. the area table, which is pure and consumes no seeds --- */
  say('// ---- AreaTests ----');
  /* The C# table's floors, for the same reason as every other list in this file: it pins 15, and this
     page was sampling 20. Neither number is wrong - both are past the last Area3 boundary and both are
     Final - but they are DIFFERENT rows, and a paste of the page would have replaced a real boundary
     case with one that tests nothing new. 15 is the floor immediately after Area3 ends, which is the
     interesting one; 100 tests the same branch with a bigger number. */
  for(const f of [1,4,5,8,9,12,13,14,15,100]){
    const restore=atFloor(f);
    say('//   floor '+String(f).padStart(3)+'  '+areaForFloor()+
        '  mix '+JSON.stringify(AREA_MIX[areaForFloor()]));
    restore();
  }

  /* --- the ROOM-SCALED numbers, at three room sizes, and the small one is the point ---

     This section exists because of a bug the other sections could not see. Every number above is a
     constant or a function of a SEED, so a name-comparison catches a drift in one. The room-scaled
     numbers are neither: `swerveDeadzone()` reads `roomW()*0.25` and no amount of grepping finds it.

     And the fix for a frozen room number REPRODUCED the bug it was fixing. `SWERVE_FULL_BASE` was
     written as `roomW()*0.55` in the same declaration as `swerveDeadzone()=()=>roomW()*0.25` - one a
     function, one a value captured once at load. In a 1680-wide room the deadzone correctly read 420
     and the ramp silently stayed at the standard room's 385px, because that is what was in scope when
     the file loaded. Measured:

         700x450   deadzone 175   full 560
        1680x760   deadzone 420   full  805     <- wanted 1344
         350x225   deadzone  88   full  281

     The assertion in the suite was `swerveFull()>swerveDeadzone()`, and it passed: 805 > 420 is true
     and so is 1344 > 420. A check that a quantity is non-empty cannot tell a quantity that follows its
     input from one that is constant. So the page emits THREE sizes, and the third is SMALLER than
     standard on purpose - a constant captured at load reads correctly in the room that existed at load
     and nowhere else, so only a room that disagrees can see it. */
  say('// ---- RoomScaledParityTests ----');
  say('// [TestCase(w, h, aggroRange, swerveDeadzone, swerveFullBase, swerveFull)]');
  {
    const restore=atFloor(run.floor);
    for(const [w,h] of [[700,450],[1680,760],[350,225]]){
      const r=currentRoom();
      r.bounds=roomBounds(w,h);
      r.cx=r.bounds.l+r.bounds.w/2; r.cy=r.bounds.t+r.bounds.h/2;
      syncRoomBounds();
      say(`//   ${w}x${h}  aggro ${aggroRange()}  deadzone ${swerveDeadzone()}`+
          `  rampBase ${swerveFullBase()}  full ${swerveFull()}`);
    }
    /* and the spawn dials, which must NOT move with the room. They are offsets, not fractions, and
       printing them here is what makes that visible: if one of these ever starts tracking the room,
       the row above it is where it shows. */
    say('//   spawn offsets are room-independent by design: '+
        [SPAWN_MARGIN,SPAWN_MID,SPAWN_SEP,SPAWN_DOOR,SPAWN_FAR].join(', '));
    restore();
  }

  /* PUT THE GAME BACK, before rendering anything. Everything above is a question about the simulation
     and none of it should survive the page: a run, and the seed that run was on. Without this the
     page leaves a started run and a rewritten RNG behind it, which is invisible (the title screen
     redraws anyway) and exactly the kind of state bleed this project's own notes keep warning about. */
  window.run=savedRun; Rnd.set(savedSeed);

  const text=out.join('\n');
  const pre=document.createElement('pre');
  pre.id='parityOut';
  pre.style.cssText='position:fixed;inset:0;z-index:9999;margin:0;padding:16px;overflow:auto;'+
    'background:#0b0e14;color:#d6c08a;font:12px/1.35 Consolas,monospace;white-space:pre';
  pre.textContent=text;
  document.body.appendChild(pre);
  /* The copy button is here because the output is long and the whole point is that it gets pasted.
     A number a human has to select by hand across forty lines is a number that gets transcribed,
     which is the failure this page was written to remove. */
  const btn=document.createElement('button');
  btn.textContent='copy to clipboard';
  btn.style.cssText='position:fixed;right:16px;top:16px;z-index:10000;padding:8px 14px;'+
    'background:#1c2230;color:#dfe6f2;border:1px solid #3a4459;border-radius:4px;cursor:pointer;font:12px monospace';
  btn.onclick=()=>{ navigator.clipboard.writeText(window.__parityTable)
    .then(()=>{ btn.textContent='copied'; })
    .catch(()=>{ btn.textContent='select and copy manually'; }); };
  document.body.appendChild(btn);
  window.__parityTable=text;
  console.log(text);
})();