/* ?parity - EMIT THE C# PARITY TABLE FROM THE RUNNING JAVASCRIPT. [h:97-parity-1] */
if(new URLSearchParams(location.search).has('parity')) (function(){
  const out=[];
  const say=s=>out.push(s);
  /* A run object is the input every depth function reads, so this page needs one to ask the ladder anything. [h:97-parity-2] */
  const savedRun=window.run, savedSeed=Rnd.seed;
  /* THE FLOOR FIXTURE WAS SETTING THE WRONG OBJECT, and it made the generated page lie. [h:97-parity-3] */
  const atFloor=f=>{ const had=run; run={floor:f};
                     if(depthFloor()!==f) console.warn('parity: floor fixture did not take');
                     return ()=>{ run=had; }; };

  say('/* GENERATED by depths.html?parity. Paste over the rows in csharp/Depths.Tests.');
  say('   Re-run after any change to the generator, the spawn planner, the balance table or the');
  say('   per-area mix. Compare DIFF-WISE against the C# file: a row that moved without a decision');
  say('   being made is exactly the defect this page exists to surface. */');
  say('');

  /* --- 1. the dungeon generator: the 13 seeds GeneratorParityTests already pins --- */
  say('// ---- GeneratorParityTests ----');
  say('// [TestCase(seed, rooms, drawCount, signature)]');
  /* The seed list is the C# table's, not a plausible-looking one of my own. [h:97-parity-4] */
  for(const seed of [0,1,2,3,42,12345,12346,99999,2654435761,4294967295,777,31337,8675309]){
    Rnd.set(seed);
    generateDungeon();
    const rs=Object.values(rooms).filter(Boolean).sort((a,b)=>a.x-b.x||a.y-b.y);
    const sig=rs.map(r=>{
      /* `doors` is an OBJECT keyed by direction, so Object.keys sorted is the direction list - and the C# sorts those as STRINGS ordinally (N before S... [h:97-parity-5] */
      const doors=Object.keys(r.doors||{}).sort().join('');
      const marks=(r.keyReward?'K':'')+(r.goldReward?'G':'')+
                  (r.secret!==undefined&&r.secret!==null?'S'+r.secret:'');
      return r.x+','+r.y+':'+r.type[0]+':'+doors+':'+marks;
    }).join('|');
    say('//   seed '+seed+'  rooms '+rs.length+'  draws '+Rnd.calls.run);
    say('//     "'+sig+'"');
  }
  say('');

  /* --- 2. the depth ladder, which DepthLadderParityTests pins per floor --- */
  say('// ---- DepthLadderParityTests ----');
  say('// floor -> tough, rate, pack, bodies(roll=0), area');
  /* THE FLOOR LIST IS THE C# TABLE'S, for the same reason the seed list is. [h:97-parity-6] */
  for(const f of [1,2,3,4,5,6,7,8,9,10,11,12,13,14,20,30,50,100]){
    const restore=atFloor(f);
    say('//   floor '+String(f).padStart(3)+'  tough '+depthTough().toFixed(4)+
        '  rate '+depthRate().toFixed(4)+'  pack '+depthPack().toFixed(4)+
        '  bodies0 '+depthBodies(0).toFixed(4)+'  area '+areaForFloor());
    restore();
  }
  say('');

  /* 3. the spawn planner, on the seeds SpawnPlanParityTests pins --- This one needs a REAL started run, not `Rnd.set` plus `generateDungeon`. [h:97-parity-7] */
  say('// ---- SpawnPlanParityTests ----');
  say('// seed, floor, fromDir -> draws used, body count ROLLED, then x,y@distance per slot');
  say('//');
  say('// THE DRAW COUNT IS THE WHOLE PLAN, and getting this right took three corrections and one');
  say('// genuine port bug. Kept short because the long version is in PORTED.md.');
  say('//');
  say('//   1. This page measured spawnPlan() alone, which is a FIXED 320 iterations of two draws, so');
  say('//      it emitted a flat 640 on every row and disagreed with the port on four seeds. The');
  say('//      candidate loop cannot depend on anything - that is why candDraws is printed as well,');
  say('//      because a row where it is not 640 means the loop changed and every column is stale.');
  say('//   2. It then measured the whole plan but generated the dungeon TWICE (startGame already');
  say('//      generates), putting the planner at the wrong point in the stream.');
  say('//   3. With both fixed the page still read +2 to +3 high, and that turned out to be a REAL bug');
  say('//      in the port: applyTrait rolls a trait per ranged body inside spawnEnemy, and the C#');
  say('//      PlanWave never rolled one, so every gunner cost the port two draws fewer than the game.');
  say('//      Fixed in SpawnPlan.cs. This page is why it was found - the gap was a CONSTANT, which is');
  say('//      the signature of a missing step rather than of divergent randomness.');
  say('//');
  say('// `bodies` is printed because the plan ROLLS its body count rather than taking one, so the');
  say('// C# column named `count` is an OUTPUT. A row printing a requested count would invite exactly');
  say('// the comparison that produced error 2 above.');
  /* THE ROW LIST IS THE C# TABLE'S, for the third time in this file and for the same reason as the seeds and the floors: [h:97-parity-8] */
  for(const [seed,floor,fromDir] of [[1,1,'N'],[1,1,'S'],[12345,1,'N'],[12345,5,'E'],
                                     [99999,1,'N'],[99999,12,'W'],[31337,3,'N'],[42,1,'W'],
                                     [777,1,'S']]){
      /* startGame IS NEEDED - generateDungeon() alone leaves `cur` unset, so currentRoom() throws and
         the whole page dies. That is why the original code called both, and the fix is not to drop
         one but to call each exactly once. */
      /* THE STATE IS A STARTED RUN, and getting this wrong is what made every row on this page disagree with the port. [h:97-parity-9] */
      startGame(seed);
      syncRoomBounds();
      run.floor=floor;
      const before=Rnd.calls.run;
      /* one call, to measure the candidate loop in isolation. [h:97-parity-10] */
      const pts=[...spawnPlan(2,fromDir)];
      const candDraws=Rnd.calls.run-before;

      /* `spawnWave(room, fromDir)` IS THE WHOLE PLAN, and using it here instead of spawnPlan was the fix for a flat 640 - but it brought a second error... [h:97-parity-11] */
      let waveDraws=null, waveBodies=null;
      startGame(seed);
      syncRoomBounds();
      run.floor=floor;
      const beforeWave=Rnd.calls.run;
      if(typeof spawnWave==='function'){
        const room=currentRoom(), nBefore=room.enemies.length;
        spawnWave(room,fromDir);
        waveDraws=Rnd.calls.run-beforeWave;
        waveBodies=room.enemies.length-nBefore;
        /* the geometry comes from the room spawnWave just filled, so the slots and the draw count are
           from the SAME wave. Reading it from a separate spawnPlan call gave slots for a different
           wave - the plan rolls its body count, so two calls roll two counts. */
        const planned=room.spawnPlan||[];
        pts.length=0;
        for(const q of planned) pts.push(q);
      }
      /* `draws` is the column the C# table pins, and it is the WHOLE plan - the count roll, the 640 candidate draws, heavy, pack, per-body type and the... [h:97-parity-12] */
      say('//   seed '+seed+' floor '+floor+' from '+fromDir+
          '  draws '+(waveDraws===null?'?':waveDraws)+
          '  candDraws '+candDraws+
          '  bodies '+(waveBodies===null?'?':waveBodies)+
          '  -> '+
          pts.map(p=>Math.round(p.x)+','+Math.round(p.y)+'@'+Math.round(p.d)).join(' '));
    }
  say('');

  /* --- 4. the area table, which is pure and consumes no seeds --- */
  say('// ---- AreaTests ----');
  /* The C# table's floors, for the same reason as every other list in this file: [h:97-parity-13] */
  for(const f of [1,4,5,8,9,12,13,14,15,100]){
    const restore=atFloor(f);
    say('//   floor '+String(f).padStart(3)+'  '+areaForFloor()+
        '  mix '+JSON.stringify(AREA_MIX[areaForFloor()]));
    restore();
  }

  /* the ROOM-SCALED numbers, at three room sizes, and the small one is the point --- This section exists because of a bug the other sections could not... [h:97-parity-14] */
  say('// ---- RoomScaledParityTests ----');
  say('// [TestCase(w, h, aggroRange, swerveDeadzone, swerveFullBase, swerveFull)]');
  {
    const restore=atFloor(run.floor);
    for(const [w,h] of [[700,450],[1680,760],[350,225]]){
      const r=currentRoom();
      r.bounds=roomBounds(w,h);
      r.cx=r.bounds.l+r.bounds.w/2; r.cy=r.bounds.t+r.bounds.h/2;
      syncRoomBounds();
      say(`//   ${w}x${h}  aggro ${aggroRange()}  deadzone ${swerveDeadzone()}`+
          `  rampBase ${swerveFullBase()}  full ${swerveFull()}`);
    }
    /* and the spawn dials, which must NOT move with the room. They are offsets, not fractions, and
       printing them here is what makes that visible: if one of these ever starts tracking the room,
       the row above it is where it shows. */
    say('//   spawn offsets are room-independent by design: '+
        [SPAWN_MARGIN,SPAWN_MID,SPAWN_SEP,SPAWN_DOOR,SPAWN_FAR].join(', '));
    restore();
  }

  /* PUT THE GAME BACK, before rendering anything. [h:97-parity-15] */
  window.run=savedRun; Rnd.set(savedSeed);

  const text=out.join('\n');
  const pre=document.createElement('pre');
  pre.id='parityOut';
  pre.style.cssText='position:fixed;inset:0;z-index:9999;margin:0;padding:16px;overflow:auto;'+
    'background:#0b0e14;color:#d6c08a;font:12px/1.35 Consolas,monospace;white-space:pre';
  pre.textContent=text;
  document.body.appendChild(pre);
  /* The copy button is here because the output is long and the whole point is that it gets pasted.
     A number a human has to select by hand across forty lines is a number that gets transcribed,
     which is the failure this page was written to remove. */
  const btn=document.createElement('button');
  btn.textContent='copy to clipboard';
  btn.style.cssText='position:fixed;right:16px;top:16px;z-index:10000;padding:8px 14px;'+
    'background:#1c2230;color:#dfe6f2;border:1px solid #3a4459;border-radius:4px;cursor:pointer;font:12px monospace';
  btn.onclick=()=>{ navigator.clipboard.writeText(window.__parityTable)
    .then(()=>{ btn.textContent='copied'; })
    .catch(()=>{ btn.textContent='select and copy manually'; }); };
  document.body.appendChild(btn);
  window.__parityTable=text;
  console.log(text);
})();