/* ================================================================================================
   ?parity - EMIT THE C# PARITY TABLE FROM THE RUNNING JAVASCRIPT.

   Open http://127.0.0.1:8731/depths.html?parity and this prints every row the C# test suite
   hardcodes, ready to paste. Copy, diff against the C# file, paste, commit.

   WHY IT EXISTS. The parity tables in csharp/Depths.Tests are string literals, and the documented
   procedure for refreshing them is: run GeneratorSignatureDump, open the browser, read the JavaScript
   side by hand, transcribe. That procedure has three failure modes and all three have happened:

     - TRANSCRIPTION. 13 dungeon signatures, each ~18 rooms with door flags and key markers. One
       character wrong and the row is a green test asserting a value nothing produces.
     - STALENESS. The tables agree with the game as it was written. GeneratorParityTests says so
       itself: "a parity table of STALE values is worse than none, because it agrees with a game
       that no longer exists - that is how the density column in the depth-ladder table came to be
       wrong three times before anybody measured it."
     - NOT RUNNING. Nobody refreshes them unless a parity test happens to go red, which is the only
       moment the cost looks worth paying. In between, the table and the game drift.

   This removes the transcription. The ARITHMETIC that can be wrong stays in the tests - this only
   removes the copying, which is the part that has been wrong.

   IT CHECKS NOTHING, AND MUST NEVER BE MADE TO. A test that regenerates its own expected values from
   the implementation asserts nothing at all. The whole value here is a human diffing the printed
   table against the C# file and noticing that a row moved without anyone deciding it should.

   IT CHANGES NO STATE. No fixture is installed, no run is started, no global is assigned. It calls
   the same functions the game calls, on the seeds the C# tests already use, so a row that differs is
   a real difference rather than an artefact of how it was produced.

   Loaded only when `?parity` is in the URL, and deliberately NOT part of depths.html's normal path:
   it is a maintenance page, and a maintenance page that runs on every launch is a maintenance page
   whose output somebody eventually asserts against.
   ================================================================================================ */
if(new URLSearchParams(location.search).has('parity')) (function(){
  const out=[];
  const say=s=>out.push(s);
  /* A run object is the input every depth function reads, so this page needs one to ask the ladder
     anything. It is assigned and restored around each question, and nothing here reads the game's own
     state - so loading this page cannot disturb a game in progress.

     The save is taken ONCE, before anything runs, and restored once at the end. The planner section
     calls startGame twenty-one times, and startGame replaces `run` wholesale - so a per-block restore
     would be twenty-one chances to forget one, and the page's claim that it changes nothing would be
     true of every block except the one nobody re-read. */
  const savedRun=window.run, savedSeed=Rnd.seed;
  const atFloor=f=>{ window.run={floor:f};
                     return ()=>{ window.run=savedRun; }; };

  say('/* GENERATED by depths.html?parity. Paste over the rows in csharp/Depths.Tests.');
  say('   Re-run after any change to the generator, the spawn planner, the balance table or the');
  say('   per-area mix. Compare DIFF-WISE against the C# file: a row that moved without a decision');
  say('   being made is exactly the defect this page exists to surface. */');
  say('');

  /* --- 1. the dungeon generator: the 13 seeds GeneratorParityTests already pins --- */
  say('// ---- GeneratorParityTests ----');
  say('// [TestCase(seed, rooms, drawCount, signature)]');
  /* The seed list is the C# table's, not a plausible-looking one of my own. It was [.., 1234, ..]
     on the first draft - a seed I invented because thirteen rows needed filling - and that is exactly
     the failure mode this page is for: a row for a seed nothing else uses cannot be diffed against
     anything. Every seed here is one GeneratorParityTests already pins, so a paste is always
     comparable. */
  for(const seed of [0,1,2,3,42,12345,12346,99999,2654435761,4294967295,777,31337,8675309]){
    Rnd.set(seed);
    generateDungeon();
    const rs=Object.values(rooms).filter(Boolean).sort((a,b)=>a.x-b.x||a.y-b.y);
    const sig=rs.map(r=>{
      /* `doors` is an OBJECT keyed by direction, so Object.keys sorted is the direction list - and
         the C# sorts those as STRINGS ordinally (N before S before W), which a JS `.sort()` on
         single letters also does. Same order, but only by accident of both being code-unit sorts;
         Dungeon.Signature says so and pins it.

         The flags are three separate things and the middle one is not a door: `S<n>` is the SECRET
         ROOM's index, not a direction. Folding it into the direction list - which is what a first
         reading of "N:GSE" invites - is exactly the transcription error this page exists to prevent,
         and it was the error I made writing it: room 4,6 came out `n:N:G` where the C# has `n:N:GSE`.
         So `S` is emitted in the flags slot, after K and G, exactly as World.Signature orders them. */
      const doors=Object.keys(r.doors||{}).sort().join('');
      const marks=(r.keyReward?'K':'')+(r.goldReward?'G':'')+
                  (r.secret!==undefined&&r.secret!==null?'S'+r.secret:'');
      return r.x+','+r.y+':'+r.type[0]+':'+doors+':'+marks;
    }).join('|');
    say('//   seed '+seed+'  rooms '+rs.length+'  draws '+Rnd.calls.run);
    say('//     "'+sig+'"');
  }
  say('');

  /* --- 2. the depth ladder, which DepthLadderParityTests pins per floor --- */
  say('// ---- DepthLadderParityTests ----');
  say('// floor -> tough, rate, pack, bodies(roll=0), area');
  for(const f of [1,2,3,5,8,12,13,20,30,50,100]){
    const restore=atFloor(f);
    say('//   floor '+String(f).padStart(3)+'  tough '+depthTough().toFixed(4)+
        '  rate '+depthRate().toFixed(4)+'  pack '+depthPack().toFixed(4)+
        '  bodies0 '+depthBodies(0).toFixed(4)+'  area '+areaForFloor());
    restore();
  }
  say('');

  /* --- 3. the spawn planner, on the seeds SpawnPlanParityTests pins ---

     This one needs a REAL started run, not `Rnd.set` plus `generateDungeon`. The C# test says so
     itself: "The JavaScript measured from a freshly started run, and startGame consumes draws for the
     dungeon. So: seed, generate a floor to burn the same stream, and only then plan." startGame also
     places `cur`, which `currentRoom()` reads through `entryPoint()`, so calling spawnPlan without it
     threw on an undefined room rather than producing a wrong row.

     And the draw count is reported alongside the geometry, because that is the number that splits "the
     seed stream diverged" from "the geometry went wrong" before anyone reads the planner.

     startGame LEAVES A RUN BEHIND - a real one, with a dungeon, a player and a room - so the whole
     section restores the one that was there on the way in. The header's claim that this page changes
     no state has to mean that even after twenty-one startGame calls, which is why the save is taken
     once at the top and put back at the end rather than trusted to each block. */
  say('// ---- SpawnPlanParityTests ----');
  say('// seed, floor, count, fromDir -> draws used, then x,y@distance per slot');
  for(const seed of [0,1,2,42,12345,777,31337]){
    for(const [floor,count,fromDir] of [[1,6,'S'],[1,6,'N'],[3,10,'E']]){
      startGame(seed);
      run.floor=floor;
      generateDungeon();
      syncRoomBounds();
      const before=Rnd.calls.run;
      const pts=spawnPlan(count,fromDir);
      say('//   seed '+seed+' floor '+floor+' count '+count+' from '+fromDir+
          '  draws '+(Rnd.calls.run-before)+'  -> '+
          pts.map(p=>Math.round(p.x)+','+Math.round(p.y)+'@'+Math.round(p.d)).join(' '));
    }
  }
  say('');

  /* --- 4. the area table, which is pure and consumes no seeds --- */
  say('// ---- AreaTests ----');
  for(const f of [1,4,5,8,9,12,13,14,20,100]){
    const restore=atFloor(f);
    say('//   floor '+String(f).padStart(3)+'  '+areaForFloor()+
        '  mix '+JSON.stringify(AREA_MIX[areaForFloor()]));
    restore();
  }

  /* PUT THE GAME BACK, before rendering anything. Everything above is a question about the simulation
     and none of it should survive the page: a run, and the seed that run was on. Without this the
     page leaves a started run and a rewritten RNG behind it, which is invisible (the title screen
     redraws anyway) and exactly the kind of state bleed this project's own notes keep warning about. */
  window.run=savedRun; Rnd.set(savedSeed);

  const text=out.join('\n');
  const pre=document.createElement('pre');
  pre.id='parityOut';
  pre.style.cssText='position:fixed;inset:0;z-index:9999;margin:0;padding:16px;overflow:auto;'+
    'background:#0b0e14;color:#d6c08a;font:12px/1.35 Consolas,monospace;white-space:pre';
  pre.textContent=text;
  document.body.appendChild(pre);
  /* The copy button is here because the output is long and the whole point is that it gets pasted.
     A number a human has to select by hand across forty lines is a number that gets transcribed,
     which is the failure this page was written to remove. */
  const btn=document.createElement('button');
  btn.textContent='copy to clipboard';
  btn.style.cssText='position:fixed;right:16px;top:16px;z-index:10000;padding:8px 14px;'+
    'background:#1c2230;color:#dfe6f2;border:1px solid #3a4459;border-radius:4px;cursor:pointer;font:12px monospace';
  btn.onclick=()=>{ navigator.clipboard.writeText(window.__parityTable)
    .then(()=>{ btn.textContent='copied'; })
    .catch(()=>{ btn.textContent='select and copy manually'; }); };
  document.body.appendChild(btn);
  window.__parityTable=text;
  console.log(text);
})();